# Generated by Django 5.1.1 on 2024-09-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Epi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CA", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=100)),
                ("fabricante", models.CharField(max_length=100)),
                ("validade", models.DateField()),
                ("quantidade", models.IntegerField()),
            ],
        ),
    ]
