# Generated by Django 5.1.1 on 2024-09-14 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=14)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.cargo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emprestimo", models.DateField()),
                ("data_devolucao", models.DateField(blank=True, null=True)),
                ("prazo_uso", models.IntegerField()),
                (
                    "motivo_devolucao",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.colaborador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EPIGenerico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("prazo_dias", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ListaEPIGenerico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.cargo"
                    ),
                ),
                (
                    "epi_generico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.epigenerico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtd_estoque", models.IntegerField()),
                ("numero_ca", models.CharField(max_length=255)),
                ("data_validade_ca", models.DateField()),
                (
                    "epi_generico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.epigenerico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Epi",
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.produto"
            ),
        ),
        migrations.AddField(
            model_name="emprestimo",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.usuario"
            ),
        ),
    ]
